---

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: formulario-inventario-app
    environment:
      - VITE_API_URL=http://localhost:4000
    ports:
      - "3003:3000"